language: node_js
node_js:
  - "16"
dist: trusty
sudo: required

before_script:
  - npm install -g --silent @angular/cli

script:
  - npm run lint-silent
  - npm run test-headless
  - bash scripts/build.sh $BUILD_ENV

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "staging-squac.pnsn.org"
    region: "us-west-2"
    skip_cleanup: true
    local_dir: dist
    on:
      branch: staging
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "squac.pnsn.org"
    region: "us-west-2"
    skip_cleanup: true
    local_dir: dist
    on:
      branch: main
