language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
  
before_script:
  - npm install -g --silent @angular/cli
  
script:
  - npm run lint
  - npm run test-headless
  - ng build --prod 

before_deploy:
  - pip install awscli --upgrade --user

deploy:
  - provider: script
    script: ~/.local/bin/aws s3 sync dist s3://staging-squac.pnsn.org --region=us-west-2 --delete 
    skip_cleanup: true
    on: 
      branch: staging
  - provider: script
    script: ~/.local/bin/aws s3 sync dist s3://squac.pnsn.org --region=us-west-2 --delete 
    skip_cleanup: true
    on: 
      branch: main
