language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
  
before_script:
  - npm install -g @angular/cli
  
script:
  - npm run lint
  - npm run test-headless
  - npm run build --prod 

deploy:
  - provider: script
    install: pip install awscli
    script: aws s3 sync dist s3://staging-squac.pnsn.org --region=us-west-2 --delete 
    skip_cleanup: true
    on: 
      branch: staging
  - provider: script
    script: ~/.local/bin/aws s3 sync dist s3://squac.pnsn.org --region=us-west-2 --delete 
    skip_cleanup: true
    on: 
      branch: main
